version: "3"

services:
  database:
    container_name: world-db
    image: mariadb:jammy
    ports:
      - 3306:3306
    volumes:
      - world-db:/var/lib/mysql
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=user-password
      - MARIADB_ROOT_PASSWORD=root-secret-password


  phpmyadmin:
    depends_on:
      - database
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  world-db:
    external: true